name: CI - Build and Static Analysis

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cppcheck cmake

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j $(nproc)

    - name: Static Analysis with cppcheck
      run: |
        cppcheck --enable=all --suppress=unusedFunction build/main build/tests/gpio_test

    # - name: Archive Production Artifact (Optional)
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: production-build
    #     path: |
    #       build/main
    #       build/tests/gpio_test
    #     if-no-files-behavior: ignore
